### PR TITLE
Add back metadata

### PR DESCRIPTION
**Pull request by gewarren**
Removed in https://github.com/Azure-Samples/iot-reliable-edge-relay/commit/e3be7213a0fcb3d981ec70bcff643623a32955c4.

### CODE REVIEW

**Comment by gewarren** [comment]
@ChenCheng368 @WilliamBerryiii Can you merge this to add the sample back to the samples browser?

**Comment by gewarren** [comment]
I went ahead and removed our broken links to this sample's URL on learn.microsoft.com/samples, so I'll close this PR.

**Comment by WilliamBerryiii** [comment]
@gewarren - sorry for missing this PR ... we've been wildly busy and I forgot to link this repos PRs and Issues to our internal team tracker. Thanks much for trying to close the loop on things!

**Comment by gewarren** [comment]
@WilliamBerryiii Ah okay, I'll reopen then in case you didn't mean to remove this sample from the sample browser.

**Review by WilliamBerryiii — APPROVED** [review]
LGTM!

**Pull request merged**
